// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/smscv1/adapter.proto

package smscv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMSAdapterService_SubmitMT_FullMethodName         = "/smsc.v1.SMSAdapterService/SubmitMT"
	SMSAdapterService_StreamDeliveries_FullMethodName = "/smsc.v1.SMSAdapterService/StreamDeliveries"
	SMSAdapterService_GetStatus_FullMethodName        = "/smsc.v1.SMSAdapterService/GetStatus"
	SMSAdapterService_CancelMT_FullMethodName         = "/smsc.v1.SMSAdapterService/CancelMT"
)

// SMSAdapterServiceClient is the client API for SMSAdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SMSAdapterService is implemented by downstream adapters (SS7, HTTP, etc.).
// The SMSC gateway connects as a gRPC client.
type SMSAdapterServiceClient interface {
	// Submit an MT-SMS for delivery.
	SubmitMT(ctx context.Context, in *SubmitMTRequest, opts ...grpc.CallOption) (*SubmitMTResponse, error)
	// Server-streaming channel for MO-SMS, DLRs, and alerts from the network.
	StreamDeliveries(ctx context.Context, in *StreamDeliveriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryMessage], error)
	// Query adapter health and link status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AdapterStatus, error)
	// Cancel a previously submitted MT-SMS.
	CancelMT(ctx context.Context, in *CancelMTRequest, opts ...grpc.CallOption) (*CancelMTResponse, error)
}

type sMSAdapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSMSAdapterServiceClient(cc grpc.ClientConnInterface) SMSAdapterServiceClient {
	return &sMSAdapterServiceClient{cc}
}

func (c *sMSAdapterServiceClient) SubmitMT(ctx context.Context, in *SubmitMTRequest, opts ...grpc.CallOption) (*SubmitMTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMTResponse)
	err := c.cc.Invoke(ctx, SMSAdapterService_SubmitMT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSAdapterServiceClient) StreamDeliveries(ctx context.Context, in *StreamDeliveriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SMSAdapterService_ServiceDesc.Streams[0], SMSAdapterService_StreamDeliveries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDeliveriesRequest, DeliveryMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SMSAdapterService_StreamDeliveriesClient = grpc.ServerStreamingClient[DeliveryMessage]

func (c *sMSAdapterServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AdapterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdapterStatus)
	err := c.cc.Invoke(ctx, SMSAdapterService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMSAdapterServiceClient) CancelMT(ctx context.Context, in *CancelMTRequest, opts ...grpc.CallOption) (*CancelMTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMTResponse)
	err := c.cc.Invoke(ctx, SMSAdapterService_CancelMT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSAdapterServiceServer is the server API for SMSAdapterService service.
// All implementations must embed UnimplementedSMSAdapterServiceServer
// for forward compatibility.
//
// SMSAdapterService is implemented by downstream adapters (SS7, HTTP, etc.).
// The SMSC gateway connects as a gRPC client.
type SMSAdapterServiceServer interface {
	// Submit an MT-SMS for delivery.
	SubmitMT(context.Context, *SubmitMTRequest) (*SubmitMTResponse, error)
	// Server-streaming channel for MO-SMS, DLRs, and alerts from the network.
	StreamDeliveries(*StreamDeliveriesRequest, grpc.ServerStreamingServer[DeliveryMessage]) error
	// Query adapter health and link status.
	GetStatus(context.Context, *GetStatusRequest) (*AdapterStatus, error)
	// Cancel a previously submitted MT-SMS.
	CancelMT(context.Context, *CancelMTRequest) (*CancelMTResponse, error)
	mustEmbedUnimplementedSMSAdapterServiceServer()
}

// UnimplementedSMSAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMSAdapterServiceServer struct{}

func (UnimplementedSMSAdapterServiceServer) SubmitMT(context.Context, *SubmitMTRequest) (*SubmitMTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMT not implemented")
}
func (UnimplementedSMSAdapterServiceServer) StreamDeliveries(*StreamDeliveriesRequest, grpc.ServerStreamingServer[DeliveryMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamDeliveries not implemented")
}
func (UnimplementedSMSAdapterServiceServer) GetStatus(context.Context, *GetStatusRequest) (*AdapterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSMSAdapterServiceServer) CancelMT(context.Context, *CancelMTRequest) (*CancelMTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMT not implemented")
}
func (UnimplementedSMSAdapterServiceServer) mustEmbedUnimplementedSMSAdapterServiceServer() {}
func (UnimplementedSMSAdapterServiceServer) testEmbeddedByValue()                           {}

// UnsafeSMSAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMSAdapterServiceServer will
// result in compilation errors.
type UnsafeSMSAdapterServiceServer interface {
	mustEmbedUnimplementedSMSAdapterServiceServer()
}

func RegisterSMSAdapterServiceServer(s grpc.ServiceRegistrar, srv SMSAdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedSMSAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMSAdapterService_ServiceDesc, srv)
}

func _SMSAdapterService_SubmitMT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSAdapterServiceServer).SubmitMT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSAdapterService_SubmitMT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSAdapterServiceServer).SubmitMT(ctx, req.(*SubmitMTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSAdapterService_StreamDeliveries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDeliveriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SMSAdapterServiceServer).StreamDeliveries(m, &grpc.GenericServerStream[StreamDeliveriesRequest, DeliveryMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SMSAdapterService_StreamDeliveriesServer = grpc.ServerStreamingServer[DeliveryMessage]

func _SMSAdapterService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSAdapterServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSAdapterService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSAdapterServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMSAdapterService_CancelMT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSAdapterServiceServer).CancelMT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSAdapterService_CancelMT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSAdapterServiceServer).CancelMT(ctx, req.(*CancelMTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMSAdapterService_ServiceDesc is the grpc.ServiceDesc for SMSAdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMSAdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smsc.v1.SMSAdapterService",
	HandlerType: (*SMSAdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMT",
			Handler:    _SMSAdapterService_SubmitMT_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SMSAdapterService_GetStatus_Handler,
		},
		{
			MethodName: "CancelMT",
			Handler:    _SMSAdapterService_CancelMT_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeliveries",
			Handler:       _SMSAdapterService_StreamDeliveries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/smscv1/adapter.proto",
}
