// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/smscv1/adapter.proto

package smscv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryType int32

const (
	DeliveryType_DELIVERY_TYPE_UNSPECIFIED DeliveryType = 0
	DeliveryType_MO_SMS                    DeliveryType = 1
	DeliveryType_DLR                       DeliveryType = 2
	DeliveryType_ALERT                     DeliveryType = 3
)

// Enum value maps for DeliveryType.
var (
	DeliveryType_name = map[int32]string{
		0: "DELIVERY_TYPE_UNSPECIFIED",
		1: "MO_SMS",
		2: "DLR",
		3: "ALERT",
	}
	DeliveryType_value = map[string]int32{
		"DELIVERY_TYPE_UNSPECIFIED": 0,
		"MO_SMS":                    1,
		"DLR":                       2,
		"ALERT":                     3,
	}
)

func (x DeliveryType) Enum() *DeliveryType {
	p := new(DeliveryType)
	*p = x
	return p
}

func (x DeliveryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smscv1_adapter_proto_enumTypes[0].Descriptor()
}

func (DeliveryType) Type() protoreflect.EnumType {
	return &file_proto_smscv1_adapter_proto_enumTypes[0]
}

func (x DeliveryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryType.Descriptor instead.
func (DeliveryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{0}
}

type SubmitMTRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SourceAddr     string                 `protobuf:"bytes,2,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	SourceAddrTon  uint32                 `protobuf:"varint,3,opt,name=source_addr_ton,json=sourceAddrTon,proto3" json:"source_addr_ton,omitempty"`
	SourceAddrNpi  uint32                 `protobuf:"varint,4,opt,name=source_addr_npi,json=sourceAddrNpi,proto3" json:"source_addr_npi,omitempty"`
	DestAddr       string                 `protobuf:"bytes,5,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	DestAddrTon    uint32                 `protobuf:"varint,6,opt,name=dest_addr_ton,json=destAddrTon,proto3" json:"dest_addr_ton,omitempty"`
	DestAddrNpi    uint32                 `protobuf:"varint,7,opt,name=dest_addr_npi,json=destAddrNpi,proto3" json:"dest_addr_npi,omitempty"`
	Payload        []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	DataCoding     uint32                 `protobuf:"varint,9,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"`
	RegisterDlr    bool                   `protobuf:"varint,10,opt,name=register_dlr,json=registerDlr,proto3" json:"register_dlr,omitempty"`
	EsmClass       uint32                 `protobuf:"varint,11,opt,name=esm_class,json=esmClass,proto3" json:"esm_class,omitempty"`
	ProtocolId     uint32                 `protobuf:"varint,12,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	Priority       uint32                 `protobuf:"varint,13,opt,name=priority,proto3" json:"priority,omitempty"`
	ValidityPeriod string                 `protobuf:"bytes,14,opt,name=validity_period,json=validityPeriod,proto3" json:"validity_period,omitempty"`
	Tlvs           map[string][]byte      `protobuf:"bytes,15,rep,name=tlvs,proto3" json:"tlvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitMTRequest) Reset() {
	*x = SubmitMTRequest{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMTRequest) ProtoMessage() {}

func (x *SubmitMTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMTRequest.ProtoReflect.Descriptor instead.
func (*SubmitMTRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitMTRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SubmitMTRequest) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *SubmitMTRequest) GetSourceAddrTon() uint32 {
	if x != nil {
		return x.SourceAddrTon
	}
	return 0
}

func (x *SubmitMTRequest) GetSourceAddrNpi() uint32 {
	if x != nil {
		return x.SourceAddrNpi
	}
	return 0
}

func (x *SubmitMTRequest) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *SubmitMTRequest) GetDestAddrTon() uint32 {
	if x != nil {
		return x.DestAddrTon
	}
	return 0
}

func (x *SubmitMTRequest) GetDestAddrNpi() uint32 {
	if x != nil {
		return x.DestAddrNpi
	}
	return 0
}

func (x *SubmitMTRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitMTRequest) GetDataCoding() uint32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

func (x *SubmitMTRequest) GetRegisterDlr() bool {
	if x != nil {
		return x.RegisterDlr
	}
	return false
}

func (x *SubmitMTRequest) GetEsmClass() uint32 {
	if x != nil {
		return x.EsmClass
	}
	return 0
}

func (x *SubmitMTRequest) GetProtocolId() uint32 {
	if x != nil {
		return x.ProtocolId
	}
	return 0
}

func (x *SubmitMTRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitMTRequest) GetValidityPeriod() string {
	if x != nil {
		return x.ValidityPeriod
	}
	return ""
}

func (x *SubmitMTRequest) GetTlvs() map[string][]byte {
	if x != nil {
		return x.Tlvs
	}
	return nil
}

type SubmitMTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMTResponse) Reset() {
	*x = SubmitMTResponse{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMTResponse) ProtoMessage() {}

func (x *SubmitMTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMTResponse.ProtoReflect.Descriptor instead.
func (*SubmitMTResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitMTResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SubmitMTResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SubmitMTResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StreamDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MaxInflight   uint32                 `protobuf:"varint,2,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDeliveriesRequest) Reset() {
	*x = StreamDeliveriesRequest{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDeliveriesRequest) ProtoMessage() {}

func (x *StreamDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*StreamDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDeliveriesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamDeliveriesRequest) GetMaxInflight() uint32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

type DeliveryMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId        string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Type              DeliveryType           `protobuf:"varint,2,opt,name=type,proto3,enum=smsc.v1.DeliveryType" json:"type,omitempty"`
	SourceAddr        string                 `protobuf:"bytes,3,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	SourceAddrTon     uint32                 `protobuf:"varint,4,opt,name=source_addr_ton,json=sourceAddrTon,proto3" json:"source_addr_ton,omitempty"`
	SourceAddrNpi     uint32                 `protobuf:"varint,5,opt,name=source_addr_npi,json=sourceAddrNpi,proto3" json:"source_addr_npi,omitempty"`
	DestAddr          string                 `protobuf:"bytes,6,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	DestAddrTon       uint32                 `protobuf:"varint,7,opt,name=dest_addr_ton,json=destAddrTon,proto3" json:"dest_addr_ton,omitempty"`
	DestAddrNpi       uint32                 `protobuf:"varint,8,opt,name=dest_addr_npi,json=destAddrNpi,proto3" json:"dest_addr_npi,omitempty"`
	Payload           []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	DataCoding        uint32                 `protobuf:"varint,10,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"`
	EsmClass          uint32                 `protobuf:"varint,11,opt,name=esm_class,json=esmClass,proto3" json:"esm_class,omitempty"`
	ProtocolId        uint32                 `protobuf:"varint,12,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	OriginalMessageId string                 `protobuf:"bytes,13,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	DlrStatus         string                 `protobuf:"bytes,14,opt,name=dlr_status,json=dlrStatus,proto3" json:"dlr_status,omitempty"`
	DlrErrorCode      string                 `protobuf:"bytes,15,opt,name=dlr_error_code,json=dlrErrorCode,proto3" json:"dlr_error_code,omitempty"`
	DlrDoneDate       string                 `protobuf:"bytes,16,opt,name=dlr_done_date,json=dlrDoneDate,proto3" json:"dlr_done_date,omitempty"`
	AlertMsisdn       string                 `protobuf:"bytes,17,opt,name=alert_msisdn,json=alertMsisdn,proto3" json:"alert_msisdn,omitempty"`
	Tlvs              map[string][]byte      `protobuf:"bytes,18,rep,name=tlvs,proto3" json:"tlvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeliveryMessage) Reset() {
	*x = DeliveryMessage{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMessage) ProtoMessage() {}

func (x *DeliveryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMessage.ProtoReflect.Descriptor instead.
func (*DeliveryMessage) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryMessage) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryMessage) GetType() DeliveryType {
	if x != nil {
		return x.Type
	}
	return DeliveryType_DELIVERY_TYPE_UNSPECIFIED
}

func (x *DeliveryMessage) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *DeliveryMessage) GetSourceAddrTon() uint32 {
	if x != nil {
		return x.SourceAddrTon
	}
	return 0
}

func (x *DeliveryMessage) GetSourceAddrNpi() uint32 {
	if x != nil {
		return x.SourceAddrNpi
	}
	return 0
}

func (x *DeliveryMessage) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *DeliveryMessage) GetDestAddrTon() uint32 {
	if x != nil {
		return x.DestAddrTon
	}
	return 0
}

func (x *DeliveryMessage) GetDestAddrNpi() uint32 {
	if x != nil {
		return x.DestAddrNpi
	}
	return 0
}

func (x *DeliveryMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeliveryMessage) GetDataCoding() uint32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

func (x *DeliveryMessage) GetEsmClass() uint32 {
	if x != nil {
		return x.EsmClass
	}
	return 0
}

func (x *DeliveryMessage) GetProtocolId() uint32 {
	if x != nil {
		return x.ProtocolId
	}
	return 0
}

func (x *DeliveryMessage) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *DeliveryMessage) GetDlrStatus() string {
	if x != nil {
		return x.DlrStatus
	}
	return ""
}

func (x *DeliveryMessage) GetDlrErrorCode() string {
	if x != nil {
		return x.DlrErrorCode
	}
	return ""
}

func (x *DeliveryMessage) GetDlrDoneDate() string {
	if x != nil {
		return x.DlrDoneDate
	}
	return ""
}

func (x *DeliveryMessage) GetAlertMsisdn() string {
	if x != nil {
		return x.AlertMsisdn
	}
	return ""
}

func (x *DeliveryMessage) GetTlvs() map[string][]byte {
	if x != nil {
		return x.Tlvs
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{4}
}

type AdapterStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdapterId      string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,2,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	Healthy        bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Links          []*LinkStatus          `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	MtSubmitted    int64                  `protobuf:"varint,5,opt,name=mt_submitted,json=mtSubmitted,proto3" json:"mt_submitted,omitempty"`
	MtDelivered    int64                  `protobuf:"varint,6,opt,name=mt_delivered,json=mtDelivered,proto3" json:"mt_delivered,omitempty"`
	MtFailed       int64                  `protobuf:"varint,7,opt,name=mt_failed,json=mtFailed,proto3" json:"mt_failed,omitempty"`
	MoReceived     int64                  `protobuf:"varint,8,opt,name=mo_received,json=moReceived,proto3" json:"mo_received,omitempty"`
	DlrReceived    int64                  `protobuf:"varint,9,opt,name=dlr_received,json=dlrReceived,proto3" json:"dlr_received,omitempty"`
	ActiveDialogs  int64                  `protobuf:"varint,10,opt,name=active_dialogs,json=activeDialogs,proto3" json:"active_dialogs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdapterStatus) Reset() {
	*x = AdapterStatus{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterStatus) ProtoMessage() {}

func (x *AdapterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterStatus.ProtoReflect.Descriptor instead.
func (*AdapterStatus) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *AdapterStatus) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *AdapterStatus) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *AdapterStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AdapterStatus) GetLinks() []*LinkStatus {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *AdapterStatus) GetMtSubmitted() int64 {
	if x != nil {
		return x.MtSubmitted
	}
	return 0
}

func (x *AdapterStatus) GetMtDelivered() int64 {
	if x != nil {
		return x.MtDelivered
	}
	return 0
}

func (x *AdapterStatus) GetMtFailed() int64 {
	if x != nil {
		return x.MtFailed
	}
	return 0
}

func (x *AdapterStatus) GetMoReceived() int64 {
	if x != nil {
		return x.MoReceived
	}
	return 0
}

func (x *AdapterStatus) GetDlrReceived() int64 {
	if x != nil {
		return x.DlrReceived
	}
	return 0
}

func (x *AdapterStatus) GetActiveDialogs() int64 {
	if x != nil {
		return x.ActiveDialogs
	}
	return 0
}

type LinkStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	PeerAddress      string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	MessagesSent     int64                  `protobuf:"varint,4,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,5,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LinkStatus) Reset() {
	*x = LinkStatus{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatus) ProtoMessage() {}

func (x *LinkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatus.ProtoReflect.Descriptor instead.
func (*LinkStatus) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *LinkStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LinkStatus) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *LinkStatus) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *LinkStatus) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

type CancelMTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMTRequest) Reset() {
	*x = CancelMTRequest{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMTRequest) ProtoMessage() {}

func (x *CancelMTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMTRequest.ProtoReflect.Descriptor instead.
func (*CancelMTRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *CancelMTRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type CancelMTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMTResponse) Reset() {
	*x = CancelMTResponse{}
	mi := &file_proto_smscv1_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMTResponse) ProtoMessage() {}

func (x *CancelMTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMTResponse.ProtoReflect.Descriptor instead.
func (*CancelMTResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *CancelMTResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CancelMTResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_smscv1_adapter_proto protoreflect.FileDescriptor

const file_proto_smscv1_adapter_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/smscv1/adapter.proto\x12\asmsc.v1\"\xd8\x04\n" +
	"\x0fSubmitMTRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vsource_addr\x18\x02 \x01(\tR\n" +
	"sourceAddr\x12&\n" +
	"\x0fsource_addr_ton\x18\x03 \x01(\rR\rsourceAddrTon\x12&\n" +
	"\x0fsource_addr_npi\x18\x04 \x01(\rR\rsourceAddrNpi\x12\x1b\n" +
	"\tdest_addr\x18\x05 \x01(\tR\bdestAddr\x12\"\n" +
	"\rdest_addr_ton\x18\x06 \x01(\rR\vdestAddrTon\x12\"\n" +
	"\rdest_addr_npi\x18\a \x01(\rR\vdestAddrNpi\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1f\n" +
	"\vdata_coding\x18\t \x01(\rR\n" +
	"dataCoding\x12!\n" +
	"\fregister_dlr\x18\n" +
	" \x01(\bR\vregisterDlr\x12\x1b\n" +
	"\tesm_class\x18\v \x01(\rR\besmClass\x12\x1f\n" +
	"\vprotocol_id\x18\f \x01(\rR\n" +
	"protocolId\x12\x1a\n" +
	"\bpriority\x18\r \x01(\rR\bpriority\x12'\n" +
	"\x0fvalidity_period\x18\x0e \x01(\tR\x0evalidityPeriod\x126\n" +
	"\x04tlvs\x18\x0f \x03(\v2\".smsc.v1.SubmitMTRequest.TlvsEntryR\x04tlvs\x1a7\n" +
	"\tTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"n\n" +
	"\x10SubmitMTResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Y\n" +
	"\x17StreamDeliveriesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fmax_inflight\x18\x02 \x01(\rR\vmaxInflight\"\xd9\x05\n" +
	"\x0fDeliveryMessage\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.smsc.v1.DeliveryTypeR\x04type\x12\x1f\n" +
	"\vsource_addr\x18\x03 \x01(\tR\n" +
	"sourceAddr\x12&\n" +
	"\x0fsource_addr_ton\x18\x04 \x01(\rR\rsourceAddrTon\x12&\n" +
	"\x0fsource_addr_npi\x18\x05 \x01(\rR\rsourceAddrNpi\x12\x1b\n" +
	"\tdest_addr\x18\x06 \x01(\tR\bdestAddr\x12\"\n" +
	"\rdest_addr_ton\x18\a \x01(\rR\vdestAddrTon\x12\"\n" +
	"\rdest_addr_npi\x18\b \x01(\rR\vdestAddrNpi\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x1f\n" +
	"\vdata_coding\x18\n" +
	" \x01(\rR\n" +
	"dataCoding\x12\x1b\n" +
	"\tesm_class\x18\v \x01(\rR\besmClass\x12\x1f\n" +
	"\vprotocol_id\x18\f \x01(\rR\n" +
	"protocolId\x12.\n" +
	"\x13original_message_id\x18\r \x01(\tR\x11originalMessageId\x12\x1d\n" +
	"\n" +
	"dlr_status\x18\x0e \x01(\tR\tdlrStatus\x12$\n" +
	"\x0edlr_error_code\x18\x0f \x01(\tR\fdlrErrorCode\x12\"\n" +
	"\rdlr_done_date\x18\x10 \x01(\tR\vdlrDoneDate\x12!\n" +
	"\falert_msisdn\x18\x11 \x01(\tR\valertMsisdn\x126\n" +
	"\x04tlvs\x18\x12 \x03(\v2\".smsc.v1.DeliveryMessage.TlvsEntryR\x04tlvs\x1a7\n" +
	"\tTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x12\n" +
	"\x10GetStatusRequest\"\xea\x02\n" +
	"\rAdapterStatus\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12'\n" +
	"\x0fadapter_version\x18\x02 \x01(\tR\x0eadapterVersion\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12)\n" +
	"\x05links\x18\x04 \x03(\v2\x13.smsc.v1.LinkStatusR\x05links\x12!\n" +
	"\fmt_submitted\x18\x05 \x01(\x03R\vmtSubmitted\x12!\n" +
	"\fmt_delivered\x18\x06 \x01(\x03R\vmtDelivered\x12\x1b\n" +
	"\tmt_failed\x18\a \x01(\x03R\bmtFailed\x12\x1f\n" +
	"\vmo_received\x18\b \x01(\x03R\n" +
	"moReceived\x12!\n" +
	"\fdlr_received\x18\t \x01(\x03R\vdlrReceived\x12%\n" +
	"\x0eactive_dialogs\x18\n" +
	" \x01(\x03R\ractiveDialogs\"\xab\x01\n" +
	"\n" +
	"LinkStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fpeer_address\x18\x03 \x01(\tR\vpeerAddress\x12#\n" +
	"\rmessages_sent\x18\x04 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\x05 \x01(\x03R\x10messagesReceived\"0\n" +
	"\x0fCancelMTRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"O\n" +
	"\x10CancelMTResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*M\n" +
	"\fDeliveryType\x12\x1d\n" +
	"\x19DELIVERY_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MO_SMS\x10\x01\x12\a\n" +
	"\x03DLR\x10\x02\x12\t\n" +
	"\x05ALERT\x10\x032\xa7\x02\n" +
	"\x11SMSAdapterService\x12?\n" +
	"\bSubmitMT\x12\x18.smsc.v1.SubmitMTRequest\x1a\x19.smsc.v1.SubmitMTResponse\x12P\n" +
	"\x10StreamDeliveries\x12 .smsc.v1.StreamDeliveriesRequest\x1a\x18.smsc.v1.DeliveryMessage0\x01\x12>\n" +
	"\tGetStatus\x12\x19.smsc.v1.GetStatusRequest\x1a\x16.smsc.v1.AdapterStatus\x12?\n" +
	"\bCancelMT\x12\x18.smsc.v1.CancelMTRequest\x1a\x19.smsc.v1.CancelMTResponseB(Z&github.com/idnteq/go-smsc/proto/smscv1b\x06proto3"

var (
	file_proto_smscv1_adapter_proto_rawDescOnce sync.Once
	file_proto_smscv1_adapter_proto_rawDescData []byte
)

func file_proto_smscv1_adapter_proto_rawDescGZIP() []byte {
	file_proto_smscv1_adapter_proto_rawDescOnce.Do(func() {
		file_proto_smscv1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smscv1_adapter_proto_rawDesc), len(file_proto_smscv1_adapter_proto_rawDesc)))
	})
	return file_proto_smscv1_adapter_proto_rawDescData
}

var file_proto_smscv1_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_smscv1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_smscv1_adapter_proto_goTypes = []any{
	(DeliveryType)(0),               // 0: smsc.v1.DeliveryType
	(*SubmitMTRequest)(nil),         // 1: smsc.v1.SubmitMTRequest
	(*SubmitMTResponse)(nil),        // 2: smsc.v1.SubmitMTResponse
	(*StreamDeliveriesRequest)(nil), // 3: smsc.v1.StreamDeliveriesRequest
	(*DeliveryMessage)(nil),         // 4: smsc.v1.DeliveryMessage
	(*GetStatusRequest)(nil),        // 5: smsc.v1.GetStatusRequest
	(*AdapterStatus)(nil),           // 6: smsc.v1.AdapterStatus
	(*LinkStatus)(nil),              // 7: smsc.v1.LinkStatus
	(*CancelMTRequest)(nil),         // 8: smsc.v1.CancelMTRequest
	(*CancelMTResponse)(nil),        // 9: smsc.v1.CancelMTResponse
	nil,                             // 10: smsc.v1.SubmitMTRequest.TlvsEntry
	nil,                             // 11: smsc.v1.DeliveryMessage.TlvsEntry
}
var file_proto_smscv1_adapter_proto_depIdxs = []int32{
	10, // 0: smsc.v1.SubmitMTRequest.tlvs:type_name -> smsc.v1.SubmitMTRequest.TlvsEntry
	0,  // 1: smsc.v1.DeliveryMessage.type:type_name -> smsc.v1.DeliveryType
	11, // 2: smsc.v1.DeliveryMessage.tlvs:type_name -> smsc.v1.DeliveryMessage.TlvsEntry
	7,  // 3: smsc.v1.AdapterStatus.links:type_name -> smsc.v1.LinkStatus
	1,  // 4: smsc.v1.SMSAdapterService.SubmitMT:input_type -> smsc.v1.SubmitMTRequest
	3,  // 5: smsc.v1.SMSAdapterService.StreamDeliveries:input_type -> smsc.v1.StreamDeliveriesRequest
	5,  // 6: smsc.v1.SMSAdapterService.GetStatus:input_type -> smsc.v1.GetStatusRequest
	8,  // 7: smsc.v1.SMSAdapterService.CancelMT:input_type -> smsc.v1.CancelMTRequest
	2,  // 8: smsc.v1.SMSAdapterService.SubmitMT:output_type -> smsc.v1.SubmitMTResponse
	4,  // 9: smsc.v1.SMSAdapterService.StreamDeliveries:output_type -> smsc.v1.DeliveryMessage
	6,  // 10: smsc.v1.SMSAdapterService.GetStatus:output_type -> smsc.v1.AdapterStatus
	9,  // 11: smsc.v1.SMSAdapterService.CancelMT:output_type -> smsc.v1.CancelMTResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_smscv1_adapter_proto_init() }
func file_proto_smscv1_adapter_proto_init() {
	if File_proto_smscv1_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smscv1_adapter_proto_rawDesc), len(file_proto_smscv1_adapter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smscv1_adapter_proto_goTypes,
		DependencyIndexes: file_proto_smscv1_adapter_proto_depIdxs,
		EnumInfos:         file_proto_smscv1_adapter_proto_enumTypes,
		MessageInfos:      file_proto_smscv1_adapter_proto_msgTypes,
	}.Build()
	File_proto_smscv1_adapter_proto = out.File
	file_proto_smscv1_adapter_proto_goTypes = nil
	file_proto_smscv1_adapter_proto_depIdxs = nil
}
