// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/smscv1/common.proto

package smscv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_smscv1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_common_proto_rawDescGZIP(), []int{0}
}

type AdapterStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdapterId      string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	AdapterVersion string                 `protobuf:"bytes,2,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	Healthy        bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Links          []*LinkStatus          `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	ActiveDialogs  int64                  `protobuf:"varint,5,opt,name=active_dialogs,json=activeDialogs,proto3" json:"active_dialogs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdapterStatus) Reset() {
	*x = AdapterStatus{}
	mi := &file_proto_smscv1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterStatus) ProtoMessage() {}

func (x *AdapterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterStatus.ProtoReflect.Descriptor instead.
func (*AdapterStatus) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_common_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterStatus) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *AdapterStatus) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *AdapterStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AdapterStatus) GetLinks() []*LinkStatus {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *AdapterStatus) GetActiveDialogs() int64 {
	if x != nil {
		return x.ActiveDialogs
	}
	return 0
}

type LinkStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // up, down, inactive, pending
	PeerAddress      string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	MessagesSent     int64                  `protobuf:"varint,4,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,5,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LinkStatus) Reset() {
	*x = LinkStatus{}
	mi := &file_proto_smscv1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatus) ProtoMessage() {}

func (x *LinkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatus.ProtoReflect.Descriptor instead.
func (*LinkStatus) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_common_proto_rawDescGZIP(), []int{2}
}

func (x *LinkStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LinkStatus) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *LinkStatus) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *LinkStatus) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

var File_proto_smscv1_common_proto protoreflect.FileDescriptor

const file_proto_smscv1_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/smscv1/common.proto\x12\asmsc.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xc3\x01\n" +
	"\rAdapterStatus\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12'\n" +
	"\x0fadapter_version\x18\x02 \x01(\tR\x0eadapterVersion\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12)\n" +
	"\x05links\x18\x04 \x03(\v2\x13.smsc.v1.LinkStatusR\x05links\x12%\n" +
	"\x0eactive_dialogs\x18\x05 \x01(\x03R\ractiveDialogs\"\xab\x01\n" +
	"\n" +
	"LinkStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fpeer_address\x18\x03 \x01(\tR\vpeerAddress\x12#\n" +
	"\rmessages_sent\x18\x04 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\x05 \x01(\x03R\x10messagesReceivedB@\n" +
	"\x16com.idnteq.ss7gw.protoZ&github.com/idnteq/go-smsc/proto/smscv1b\x06proto3"

var (
	file_proto_smscv1_common_proto_rawDescOnce sync.Once
	file_proto_smscv1_common_proto_rawDescData []byte
)

func file_proto_smscv1_common_proto_rawDescGZIP() []byte {
	file_proto_smscv1_common_proto_rawDescOnce.Do(func() {
		file_proto_smscv1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smscv1_common_proto_rawDesc), len(file_proto_smscv1_common_proto_rawDesc)))
	})
	return file_proto_smscv1_common_proto_rawDescData
}

var file_proto_smscv1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_smscv1_common_proto_goTypes = []any{
	(*GetStatusRequest)(nil), // 0: smsc.v1.GetStatusRequest
	(*AdapterStatus)(nil),    // 1: smsc.v1.AdapterStatus
	(*LinkStatus)(nil),       // 2: smsc.v1.LinkStatus
}
var file_proto_smscv1_common_proto_depIdxs = []int32{
	2, // 0: smsc.v1.AdapterStatus.links:type_name -> smsc.v1.LinkStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_smscv1_common_proto_init() }
func file_proto_smscv1_common_proto_init() {
	if File_proto_smscv1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smscv1_common_proto_rawDesc), len(file_proto_smscv1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_smscv1_common_proto_goTypes,
		DependencyIndexes: file_proto_smscv1_common_proto_depIdxs,
		MessageInfos:      file_proto_smscv1_common_proto_msgTypes,
	}.Build()
	File_proto_smscv1_common_proto = out.File
	file_proto_smscv1_common_proto_goTypes = nil
	file_proto_smscv1_common_proto_depIdxs = nil
}
