// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/smscv1/management.proto

package smscv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAssociationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssociationsRequest) Reset() {
	*x = ListAssociationsRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssociationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssociationsRequest) ProtoMessage() {}

func (x *ListAssociationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssociationsRequest.ProtoReflect.Descriptor instead.
func (*ListAssociationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{0}
}

type ListAssociationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Associations  []*AssociationInfo     `protobuf:"bytes,1,rep,name=associations,proto3" json:"associations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssociationsResponse) Reset() {
	*x = ListAssociationsResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssociationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssociationsResponse) ProtoMessage() {}

func (x *ListAssociationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssociationsResponse.ProtoReflect.Descriptor instead.
func (*ListAssociationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{1}
}

func (x *ListAssociationsResponse) GetAssociations() []*AssociationInfo {
	if x != nil {
		return x.Associations
	}
	return nil
}

type AssociationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LocalAddress     string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"` // host:port
	PeerAddress      string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`    // host:port
	State            string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                   // up, down, connecting
	UptimeSeconds    int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MessagesSent     int64                  `protobuf:"varint,6,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,7,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssociationInfo) Reset() {
	*x = AssociationInfo{}
	mi := &file_proto_smscv1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociationInfo) ProtoMessage() {}

func (x *AssociationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociationInfo.ProtoReflect.Descriptor instead.
func (*AssociationInfo) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{2}
}

func (x *AssociationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssociationInfo) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *AssociationInfo) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *AssociationInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AssociationInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AssociationInfo) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *AssociationInfo) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

type AssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociationRequest) Reset() {
	*x = AssociationRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociationRequest) ProtoMessage() {}

func (x *AssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociationRequest.ProtoReflect.Descriptor instead.
func (*AssociationRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{3}
}

func (x *AssociationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AssociationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociationResponse) Reset() {
	*x = AssociationResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociationResponse) ProtoMessage() {}

func (x *AssociationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociationResponse.ProtoReflect.Descriptor instead.
func (*AssociationResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{4}
}

func (x *AssociationResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AssociationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListGTTRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGTTRulesRequest) Reset() {
	*x = ListGTTRulesRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGTTRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGTTRulesRequest) ProtoMessage() {}

func (x *ListGTTRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGTTRulesRequest.ProtoReflect.Descriptor instead.
func (*ListGTTRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{5}
}

type ListGTTRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*GTTRule             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGTTRulesResponse) Reset() {
	*x = ListGTTRulesResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGTTRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGTTRulesResponse) ProtoMessage() {}

func (x *ListGTTRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGTTRulesResponse.ProtoReflect.Descriptor instead.
func (*ListGTTRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{6}
}

func (x *ListGTTRulesResponse) GetRules() []*GTTRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type GTTRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DigitsPattern    string                 `protobuf:"bytes,2,opt,name=digits_pattern,json=digitsPattern,proto3" json:"digits_pattern,omitempty"` // e.g., "27*", "234*"
	Mask             string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`                                        // K = keep, R = replace
	RuleType         string                 `protobuf:"bytes,4,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`                // solitary, dominant, loadshared, broadcast
	PrimaryAddressId int32                  `protobuf:"varint,5,opt,name=primary_address_id,json=primaryAddressId,proto3" json:"primary_address_id,omitempty"`
	BackupAddressId  int32                  `protobuf:"varint,6,opt,name=backup_address_id,json=backupAddressId,proto3" json:"backup_address_id,omitempty"`
	PrimaryPc        string                 `protobuf:"bytes,7,opt,name=primary_pc,json=primaryPc,proto3" json:"primary_pc,omitempty"` // Point code of primary destination
	PrimarySsn       int32                  `protobuf:"varint,8,opt,name=primary_ssn,json=primarySsn,proto3" json:"primary_ssn,omitempty"`
	BackupPc         string                 `protobuf:"bytes,9,opt,name=backup_pc,json=backupPc,proto3" json:"backup_pc,omitempty"`
	BackupSsn        int32                  `protobuf:"varint,10,opt,name=backup_ssn,json=backupSsn,proto3" json:"backup_ssn,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GTTRule) Reset() {
	*x = GTTRule{}
	mi := &file_proto_smscv1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GTTRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GTTRule) ProtoMessage() {}

func (x *GTTRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GTTRule.ProtoReflect.Descriptor instead.
func (*GTTRule) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{7}
}

func (x *GTTRule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GTTRule) GetDigitsPattern() string {
	if x != nil {
		return x.DigitsPattern
	}
	return ""
}

func (x *GTTRule) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *GTTRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *GTTRule) GetPrimaryAddressId() int32 {
	if x != nil {
		return x.PrimaryAddressId
	}
	return 0
}

func (x *GTTRule) GetBackupAddressId() int32 {
	if x != nil {
		return x.BackupAddressId
	}
	return 0
}

func (x *GTTRule) GetPrimaryPc() string {
	if x != nil {
		return x.PrimaryPc
	}
	return ""
}

func (x *GTTRule) GetPrimarySsn() int32 {
	if x != nil {
		return x.PrimarySsn
	}
	return 0
}

func (x *GTTRule) GetBackupPc() string {
	if x != nil {
		return x.BackupPc
	}
	return ""
}

func (x *GTTRule) GetBackupSsn() int32 {
	if x != nil {
		return x.BackupSsn
	}
	return 0
}

type AddGTTRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *GTTRule               `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGTTRuleRequest) Reset() {
	*x = AddGTTRuleRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGTTRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGTTRuleRequest) ProtoMessage() {}

func (x *AddGTTRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGTTRuleRequest.ProtoReflect.Descriptor instead.
func (*AddGTTRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{8}
}

func (x *AddGTTRuleRequest) GetRule() *GTTRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddGTTRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGTTRuleResponse) Reset() {
	*x = AddGTTRuleResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGTTRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGTTRuleResponse) ProtoMessage() {}

func (x *AddGTTRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGTTRuleResponse.ProtoReflect.Descriptor instead.
func (*AddGTTRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{9}
}

func (x *AddGTTRuleResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddGTTRuleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RemoveGTTRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGTTRuleRequest) Reset() {
	*x = RemoveGTTRuleRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGTTRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGTTRuleRequest) ProtoMessage() {}

func (x *RemoveGTTRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGTTRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveGTTRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveGTTRuleRequest) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type RemoveGTTRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGTTRuleResponse) Reset() {
	*x = RemoveGTTRuleResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGTTRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGTTRuleResponse) ProtoMessage() {}

func (x *RemoveGTTRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGTTRuleResponse.ProtoReflect.Descriptor instead.
func (*RemoveGTTRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveGTTRuleResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoveGTTRuleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetCountersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountersRequest) Reset() {
	*x = GetCountersRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountersRequest) ProtoMessage() {}

func (x *GetCountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountersRequest.ProtoReflect.Descriptor instead.
func (*GetCountersRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{12}
}

type Counters struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MtSubmitted           int64                  `protobuf:"varint,1,opt,name=mt_submitted,json=mtSubmitted,proto3" json:"mt_submitted,omitempty"`
	MtDelivered           int64                  `protobuf:"varint,2,opt,name=mt_delivered,json=mtDelivered,proto3" json:"mt_delivered,omitempty"`
	MtFailed              int64                  `protobuf:"varint,3,opt,name=mt_failed,json=mtFailed,proto3" json:"mt_failed,omitempty"`
	MoReceived            int64                  `protobuf:"varint,4,opt,name=mo_received,json=moReceived,proto3" json:"mo_received,omitempty"`
	DlrReceived           int64                  `protobuf:"varint,5,opt,name=dlr_received,json=dlrReceived,proto3" json:"dlr_received,omitempty"`
	UssdSessionsInitiated int64                  `protobuf:"varint,6,opt,name=ussd_sessions_initiated,json=ussdSessionsInitiated,proto3" json:"ussd_sessions_initiated,omitempty"`
	UssdSessionsReceived  int64                  `protobuf:"varint,7,opt,name=ussd_sessions_received,json=ussdSessionsReceived,proto3" json:"ussd_sessions_received,omitempty"`
	UssdSessionsActive    int64                  `protobuf:"varint,8,opt,name=ussd_sessions_active,json=ussdSessionsActive,proto3" json:"ussd_sessions_active,omitempty"`
	SccpMessagesSent      int64                  `protobuf:"varint,9,opt,name=sccp_messages_sent,json=sccpMessagesSent,proto3" json:"sccp_messages_sent,omitempty"`
	SccpMessagesReceived  int64                  `protobuf:"varint,10,opt,name=sccp_messages_received,json=sccpMessagesReceived,proto3" json:"sccp_messages_received,omitempty"`
	TcapDialogsActive     int64                  `protobuf:"varint,11,opt,name=tcap_dialogs_active,json=tcapDialogsActive,proto3" json:"tcap_dialogs_active,omitempty"`
	TcapDialogsTotal      int64                  `protobuf:"varint,12,opt,name=tcap_dialogs_total,json=tcapDialogsTotal,proto3" json:"tcap_dialogs_total,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Counters) Reset() {
	*x = Counters{}
	mi := &file_proto_smscv1_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counters) ProtoMessage() {}

func (x *Counters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counters.ProtoReflect.Descriptor instead.
func (*Counters) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{13}
}

func (x *Counters) GetMtSubmitted() int64 {
	if x != nil {
		return x.MtSubmitted
	}
	return 0
}

func (x *Counters) GetMtDelivered() int64 {
	if x != nil {
		return x.MtDelivered
	}
	return 0
}

func (x *Counters) GetMtFailed() int64 {
	if x != nil {
		return x.MtFailed
	}
	return 0
}

func (x *Counters) GetMoReceived() int64 {
	if x != nil {
		return x.MoReceived
	}
	return 0
}

func (x *Counters) GetDlrReceived() int64 {
	if x != nil {
		return x.DlrReceived
	}
	return 0
}

func (x *Counters) GetUssdSessionsInitiated() int64 {
	if x != nil {
		return x.UssdSessionsInitiated
	}
	return 0
}

func (x *Counters) GetUssdSessionsReceived() int64 {
	if x != nil {
		return x.UssdSessionsReceived
	}
	return 0
}

func (x *Counters) GetUssdSessionsActive() int64 {
	if x != nil {
		return x.UssdSessionsActive
	}
	return 0
}

func (x *Counters) GetSccpMessagesSent() int64 {
	if x != nil {
		return x.SccpMessagesSent
	}
	return 0
}

func (x *Counters) GetSccpMessagesReceived() int64 {
	if x != nil {
		return x.SccpMessagesReceived
	}
	return 0
}

func (x *Counters) GetTcapDialogsActive() int64 {
	if x != nil {
		return x.TcapDialogsActive
	}
	return 0
}

func (x *Counters) GetTcapDialogsTotal() int64 {
	if x != nil {
		return x.TcapDialogsTotal
	}
	return 0
}

type ResetCountersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCountersRequest) Reset() {
	*x = ResetCountersRequest{}
	mi := &file_proto_smscv1_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCountersRequest) ProtoMessage() {}

func (x *ResetCountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCountersRequest.ProtoReflect.Descriptor instead.
func (*ResetCountersRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{14}
}

type ResetCountersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCountersResponse) Reset() {
	*x = ResetCountersResponse{}
	mi := &file_proto_smscv1_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCountersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCountersResponse) ProtoMessage() {}

func (x *ResetCountersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCountersResponse.ProtoReflect.Descriptor instead.
func (*ResetCountersResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_management_proto_rawDescGZIP(), []int{15}
}

func (x *ResetCountersResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_smscv1_management_proto protoreflect.FileDescriptor

const file_proto_smscv1_management_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/smscv1/management.proto\x12\asmsc.v1\x1a\x19proto/smscv1/common.proto\"\x19\n" +
	"\x17ListAssociationsRequest\"X\n" +
	"\x18ListAssociationsResponse\x12<\n" +
	"\fassociations\x18\x01 \x03(\v2\x18.smsc.v1.AssociationInfoR\fassociations\"\xfc\x01\n" +
	"\x0fAssociationInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x12!\n" +
	"\fpeer_address\x18\x03 \x01(\tR\vpeerAddress\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rmessages_sent\x18\x06 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\a \x01(\x03R\x10messagesReceived\"(\n" +
	"\x12AssociationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x13AssociationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13ListGTTRulesRequest\">\n" +
	"\x14ListGTTRulesResponse\x12&\n" +
	"\x05rules\x18\x01 \x03(\v2\x10.smsc.v1.GTTRuleR\x05rules\"\xc7\x02\n" +
	"\aGTTRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x0edigits_pattern\x18\x02 \x01(\tR\rdigitsPattern\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\x12\x1b\n" +
	"\trule_type\x18\x04 \x01(\tR\bruleType\x12,\n" +
	"\x12primary_address_id\x18\x05 \x01(\x05R\x10primaryAddressId\x12*\n" +
	"\x11backup_address_id\x18\x06 \x01(\x05R\x0fbackupAddressId\x12\x1d\n" +
	"\n" +
	"primary_pc\x18\a \x01(\tR\tprimaryPc\x12\x1f\n" +
	"\vprimary_ssn\x18\b \x01(\x05R\n" +
	"primarySsn\x12\x1b\n" +
	"\tbackup_pc\x18\t \x01(\tR\bbackupPc\x12\x1d\n" +
	"\n" +
	"backup_ssn\x18\n" +
	" \x01(\x05R\tbackupSsn\"9\n" +
	"\x11AddGTTRuleRequest\x12$\n" +
	"\x04rule\x18\x01 \x01(\v2\x10.smsc.v1.GTTRuleR\x04rule\"Q\n" +
	"\x12AddGTTRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"/\n" +
	"\x14RemoveGTTRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\"T\n" +
	"\x15RemoveGTTRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12GetCountersRequest\"\x93\x04\n" +
	"\bCounters\x12!\n" +
	"\fmt_submitted\x18\x01 \x01(\x03R\vmtSubmitted\x12!\n" +
	"\fmt_delivered\x18\x02 \x01(\x03R\vmtDelivered\x12\x1b\n" +
	"\tmt_failed\x18\x03 \x01(\x03R\bmtFailed\x12\x1f\n" +
	"\vmo_received\x18\x04 \x01(\x03R\n" +
	"moReceived\x12!\n" +
	"\fdlr_received\x18\x05 \x01(\x03R\vdlrReceived\x126\n" +
	"\x17ussd_sessions_initiated\x18\x06 \x01(\x03R\x15ussdSessionsInitiated\x124\n" +
	"\x16ussd_sessions_received\x18\a \x01(\x03R\x14ussdSessionsReceived\x120\n" +
	"\x14ussd_sessions_active\x18\b \x01(\x03R\x12ussdSessionsActive\x12,\n" +
	"\x12sccp_messages_sent\x18\t \x01(\x03R\x10sccpMessagesSent\x124\n" +
	"\x16sccp_messages_received\x18\n" +
	" \x01(\x03R\x14sccpMessagesReceived\x12.\n" +
	"\x13tcap_dialogs_active\x18\v \x01(\x03R\x11tcapDialogsActive\x12,\n" +
	"\x12tcap_dialogs_total\x18\f \x01(\x03R\x10tcapDialogsTotal\"\x16\n" +
	"\x14ResetCountersRequest\"/\n" +
	"\x15ResetCountersResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status2\xbc\x05\n" +
	"\x11ManagementService\x12>\n" +
	"\tGetStatus\x12\x19.smsc.v1.GetStatusRequest\x1a\x16.smsc.v1.AdapterStatus\x12W\n" +
	"\x10ListAssociations\x12 .smsc.v1.ListAssociationsRequest\x1a!.smsc.v1.ListAssociationsResponse\x12M\n" +
	"\x10StartAssociation\x12\x1b.smsc.v1.AssociationRequest\x1a\x1c.smsc.v1.AssociationResponse\x12L\n" +
	"\x0fStopAssociation\x12\x1b.smsc.v1.AssociationRequest\x1a\x1c.smsc.v1.AssociationResponse\x12K\n" +
	"\fListGTTRules\x12\x1c.smsc.v1.ListGTTRulesRequest\x1a\x1d.smsc.v1.ListGTTRulesResponse\x12E\n" +
	"\n" +
	"AddGTTRule\x12\x1a.smsc.v1.AddGTTRuleRequest\x1a\x1b.smsc.v1.AddGTTRuleResponse\x12N\n" +
	"\rRemoveGTTRule\x12\x1d.smsc.v1.RemoveGTTRuleRequest\x1a\x1e.smsc.v1.RemoveGTTRuleResponse\x12=\n" +
	"\vGetCounters\x12\x1b.smsc.v1.GetCountersRequest\x1a\x11.smsc.v1.Counters\x12N\n" +
	"\rResetCounters\x12\x1d.smsc.v1.ResetCountersRequest\x1a\x1e.smsc.v1.ResetCountersResponseB@\n" +
	"\x16com.idnteq.ss7gw.protoZ&github.com/idnteq/go-smsc/proto/smscv1b\x06proto3"

var (
	file_proto_smscv1_management_proto_rawDescOnce sync.Once
	file_proto_smscv1_management_proto_rawDescData []byte
)

func file_proto_smscv1_management_proto_rawDescGZIP() []byte {
	file_proto_smscv1_management_proto_rawDescOnce.Do(func() {
		file_proto_smscv1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smscv1_management_proto_rawDesc), len(file_proto_smscv1_management_proto_rawDesc)))
	})
	return file_proto_smscv1_management_proto_rawDescData
}

var file_proto_smscv1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_smscv1_management_proto_goTypes = []any{
	(*ListAssociationsRequest)(nil),  // 0: smsc.v1.ListAssociationsRequest
	(*ListAssociationsResponse)(nil), // 1: smsc.v1.ListAssociationsResponse
	(*AssociationInfo)(nil),          // 2: smsc.v1.AssociationInfo
	(*AssociationRequest)(nil),       // 3: smsc.v1.AssociationRequest
	(*AssociationResponse)(nil),      // 4: smsc.v1.AssociationResponse
	(*ListGTTRulesRequest)(nil),      // 5: smsc.v1.ListGTTRulesRequest
	(*ListGTTRulesResponse)(nil),     // 6: smsc.v1.ListGTTRulesResponse
	(*GTTRule)(nil),                  // 7: smsc.v1.GTTRule
	(*AddGTTRuleRequest)(nil),        // 8: smsc.v1.AddGTTRuleRequest
	(*AddGTTRuleResponse)(nil),       // 9: smsc.v1.AddGTTRuleResponse
	(*RemoveGTTRuleRequest)(nil),     // 10: smsc.v1.RemoveGTTRuleRequest
	(*RemoveGTTRuleResponse)(nil),    // 11: smsc.v1.RemoveGTTRuleResponse
	(*GetCountersRequest)(nil),       // 12: smsc.v1.GetCountersRequest
	(*Counters)(nil),                 // 13: smsc.v1.Counters
	(*ResetCountersRequest)(nil),     // 14: smsc.v1.ResetCountersRequest
	(*ResetCountersResponse)(nil),    // 15: smsc.v1.ResetCountersResponse
	(*GetStatusRequest)(nil),         // 16: smsc.v1.GetStatusRequest
	(*AdapterStatus)(nil),            // 17: smsc.v1.AdapterStatus
}
var file_proto_smscv1_management_proto_depIdxs = []int32{
	2,  // 0: smsc.v1.ListAssociationsResponse.associations:type_name -> smsc.v1.AssociationInfo
	7,  // 1: smsc.v1.ListGTTRulesResponse.rules:type_name -> smsc.v1.GTTRule
	7,  // 2: smsc.v1.AddGTTRuleRequest.rule:type_name -> smsc.v1.GTTRule
	16, // 3: smsc.v1.ManagementService.GetStatus:input_type -> smsc.v1.GetStatusRequest
	0,  // 4: smsc.v1.ManagementService.ListAssociations:input_type -> smsc.v1.ListAssociationsRequest
	3,  // 5: smsc.v1.ManagementService.StartAssociation:input_type -> smsc.v1.AssociationRequest
	3,  // 6: smsc.v1.ManagementService.StopAssociation:input_type -> smsc.v1.AssociationRequest
	5,  // 7: smsc.v1.ManagementService.ListGTTRules:input_type -> smsc.v1.ListGTTRulesRequest
	8,  // 8: smsc.v1.ManagementService.AddGTTRule:input_type -> smsc.v1.AddGTTRuleRequest
	10, // 9: smsc.v1.ManagementService.RemoveGTTRule:input_type -> smsc.v1.RemoveGTTRuleRequest
	12, // 10: smsc.v1.ManagementService.GetCounters:input_type -> smsc.v1.GetCountersRequest
	14, // 11: smsc.v1.ManagementService.ResetCounters:input_type -> smsc.v1.ResetCountersRequest
	17, // 12: smsc.v1.ManagementService.GetStatus:output_type -> smsc.v1.AdapterStatus
	1,  // 13: smsc.v1.ManagementService.ListAssociations:output_type -> smsc.v1.ListAssociationsResponse
	4,  // 14: smsc.v1.ManagementService.StartAssociation:output_type -> smsc.v1.AssociationResponse
	4,  // 15: smsc.v1.ManagementService.StopAssociation:output_type -> smsc.v1.AssociationResponse
	6,  // 16: smsc.v1.ManagementService.ListGTTRules:output_type -> smsc.v1.ListGTTRulesResponse
	9,  // 17: smsc.v1.ManagementService.AddGTTRule:output_type -> smsc.v1.AddGTTRuleResponse
	11, // 18: smsc.v1.ManagementService.RemoveGTTRule:output_type -> smsc.v1.RemoveGTTRuleResponse
	13, // 19: smsc.v1.ManagementService.GetCounters:output_type -> smsc.v1.Counters
	15, // 20: smsc.v1.ManagementService.ResetCounters:output_type -> smsc.v1.ResetCountersResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_smscv1_management_proto_init() }
func file_proto_smscv1_management_proto_init() {
	if File_proto_smscv1_management_proto != nil {
		return
	}
	file_proto_smscv1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smscv1_management_proto_rawDesc), len(file_proto_smscv1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smscv1_management_proto_goTypes,
		DependencyIndexes: file_proto_smscv1_management_proto_depIdxs,
		MessageInfos:      file_proto_smscv1_management_proto_msgTypes,
	}.Build()
	File_proto_smscv1_management_proto = out.File
	file_proto_smscv1_management_proto_goTypes = nil
	file_proto_smscv1_management_proto_depIdxs = nil
}
