// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/smscv1/management.proto

package smscv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_GetStatus_FullMethodName        = "/smsc.v1.ManagementService/GetStatus"
	ManagementService_ListAssociations_FullMethodName = "/smsc.v1.ManagementService/ListAssociations"
	ManagementService_StartAssociation_FullMethodName = "/smsc.v1.ManagementService/StartAssociation"
	ManagementService_StopAssociation_FullMethodName  = "/smsc.v1.ManagementService/StopAssociation"
	ManagementService_ListGTTRules_FullMethodName     = "/smsc.v1.ManagementService/ListGTTRules"
	ManagementService_AddGTTRule_FullMethodName       = "/smsc.v1.ManagementService/AddGTTRule"
	ManagementService_RemoveGTTRule_FullMethodName    = "/smsc.v1.ManagementService/RemoveGTTRule"
	ManagementService_GetCounters_FullMethodName      = "/smsc.v1.ManagementService/GetCounters"
	ManagementService_ResetCounters_FullMethodName    = "/smsc.v1.ManagementService/ResetCounters"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagementService provides runtime configuration and monitoring of the adapter.
type ManagementServiceClient interface {
	// Get overall adapter status including all link states.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AdapterStatus, error)
	// List all SCTP associations with their current state.
	ListAssociations(ctx context.Context, in *ListAssociationsRequest, opts ...grpc.CallOption) (*ListAssociationsResponse, error)
	// Start a stopped SCTP association.
	StartAssociation(ctx context.Context, in *AssociationRequest, opts ...grpc.CallOption) (*AssociationResponse, error)
	// Stop a running SCTP association.
	StopAssociation(ctx context.Context, in *AssociationRequest, opts ...grpc.CallOption) (*AssociationResponse, error)
	// List configured GTT rules.
	ListGTTRules(ctx context.Context, in *ListGTTRulesRequest, opts ...grpc.CallOption) (*ListGTTRulesResponse, error)
	// Add a GTT rule at runtime.
	AddGTTRule(ctx context.Context, in *AddGTTRuleRequest, opts ...grpc.CallOption) (*AddGTTRuleResponse, error)
	// Remove a GTT rule.
	RemoveGTTRule(ctx context.Context, in *RemoveGTTRuleRequest, opts ...grpc.CallOption) (*RemoveGTTRuleResponse, error)
	// Get detailed message counters.
	GetCounters(ctx context.Context, in *GetCountersRequest, opts ...grpc.CallOption) (*Counters, error)
	// Reset all counters.
	ResetCounters(ctx context.Context, in *ResetCountersRequest, opts ...grpc.CallOption) (*ResetCountersResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AdapterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdapterStatus)
	err := c.cc.Invoke(ctx, ManagementService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListAssociations(ctx context.Context, in *ListAssociationsRequest, opts ...grpc.CallOption) (*ListAssociationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssociationsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListAssociations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StartAssociation(ctx context.Context, in *AssociationRequest, opts ...grpc.CallOption) (*AssociationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssociationResponse)
	err := c.cc.Invoke(ctx, ManagementService_StartAssociation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StopAssociation(ctx context.Context, in *AssociationRequest, opts ...grpc.CallOption) (*AssociationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssociationResponse)
	err := c.cc.Invoke(ctx, ManagementService_StopAssociation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListGTTRules(ctx context.Context, in *ListGTTRulesRequest, opts ...grpc.CallOption) (*ListGTTRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGTTRulesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListGTTRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) AddGTTRule(ctx context.Context, in *AddGTTRuleRequest, opts ...grpc.CallOption) (*AddGTTRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGTTRuleResponse)
	err := c.cc.Invoke(ctx, ManagementService_AddGTTRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemoveGTTRule(ctx context.Context, in *RemoveGTTRuleRequest, opts ...grpc.CallOption) (*RemoveGTTRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveGTTRuleResponse)
	err := c.cc.Invoke(ctx, ManagementService_RemoveGTTRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetCounters(ctx context.Context, in *GetCountersRequest, opts ...grpc.CallOption) (*Counters, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Counters)
	err := c.cc.Invoke(ctx, ManagementService_GetCounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ResetCounters(ctx context.Context, in *ResetCountersRequest, opts ...grpc.CallOption) (*ResetCountersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetCountersResponse)
	err := c.cc.Invoke(ctx, ManagementService_ResetCounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// ManagementService provides runtime configuration and monitoring of the adapter.
type ManagementServiceServer interface {
	// Get overall adapter status including all link states.
	GetStatus(context.Context, *GetStatusRequest) (*AdapterStatus, error)
	// List all SCTP associations with their current state.
	ListAssociations(context.Context, *ListAssociationsRequest) (*ListAssociationsResponse, error)
	// Start a stopped SCTP association.
	StartAssociation(context.Context, *AssociationRequest) (*AssociationResponse, error)
	// Stop a running SCTP association.
	StopAssociation(context.Context, *AssociationRequest) (*AssociationResponse, error)
	// List configured GTT rules.
	ListGTTRules(context.Context, *ListGTTRulesRequest) (*ListGTTRulesResponse, error)
	// Add a GTT rule at runtime.
	AddGTTRule(context.Context, *AddGTTRuleRequest) (*AddGTTRuleResponse, error)
	// Remove a GTT rule.
	RemoveGTTRule(context.Context, *RemoveGTTRuleRequest) (*RemoveGTTRuleResponse, error)
	// Get detailed message counters.
	GetCounters(context.Context, *GetCountersRequest) (*Counters, error)
	// Reset all counters.
	ResetCounters(context.Context, *ResetCountersRequest) (*ResetCountersResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) GetStatus(context.Context, *GetStatusRequest) (*AdapterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedManagementServiceServer) ListAssociations(context.Context, *ListAssociationsRequest) (*ListAssociationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssociations not implemented")
}
func (UnimplementedManagementServiceServer) StartAssociation(context.Context, *AssociationRequest) (*AssociationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAssociation not implemented")
}
func (UnimplementedManagementServiceServer) StopAssociation(context.Context, *AssociationRequest) (*AssociationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAssociation not implemented")
}
func (UnimplementedManagementServiceServer) ListGTTRules(context.Context, *ListGTTRulesRequest) (*ListGTTRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGTTRules not implemented")
}
func (UnimplementedManagementServiceServer) AddGTTRule(context.Context, *AddGTTRuleRequest) (*AddGTTRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGTTRule not implemented")
}
func (UnimplementedManagementServiceServer) RemoveGTTRule(context.Context, *RemoveGTTRuleRequest) (*RemoveGTTRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGTTRule not implemented")
}
func (UnimplementedManagementServiceServer) GetCounters(context.Context, *GetCountersRequest) (*Counters, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCounters not implemented")
}
func (UnimplementedManagementServiceServer) ResetCounters(context.Context, *ResetCountersRequest) (*ResetCountersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetCounters not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListAssociations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssociationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListAssociations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListAssociations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListAssociations(ctx, req.(*ListAssociationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StartAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).StartAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_StartAssociation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).StartAssociation(ctx, req.(*AssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StopAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).StopAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_StopAssociation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).StopAssociation(ctx, req.(*AssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListGTTRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGTTRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListGTTRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListGTTRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListGTTRules(ctx, req.(*ListGTTRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_AddGTTRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGTTRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).AddGTTRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_AddGTTRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).AddGTTRule(ctx, req.(*AddGTTRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemoveGTTRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGTTRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemoveGTTRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemoveGTTRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemoveGTTRule(ctx, req.(*RemoveGTTRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetCounters(ctx, req.(*GetCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ResetCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ResetCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ResetCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ResetCounters(ctx, req.(*ResetCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smsc.v1.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ManagementService_GetStatus_Handler,
		},
		{
			MethodName: "ListAssociations",
			Handler:    _ManagementService_ListAssociations_Handler,
		},
		{
			MethodName: "StartAssociation",
			Handler:    _ManagementService_StartAssociation_Handler,
		},
		{
			MethodName: "StopAssociation",
			Handler:    _ManagementService_StopAssociation_Handler,
		},
		{
			MethodName: "ListGTTRules",
			Handler:    _ManagementService_ListGTTRules_Handler,
		},
		{
			MethodName: "AddGTTRule",
			Handler:    _ManagementService_AddGTTRule_Handler,
		},
		{
			MethodName: "RemoveGTTRule",
			Handler:    _ManagementService_RemoveGTTRule_Handler,
		},
		{
			MethodName: "GetCounters",
			Handler:    _ManagementService_GetCounters_Handler,
		},
		{
			MethodName: "ResetCounters",
			Handler:    _ManagementService_ResetCounters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/smscv1/management.proto",
}
