// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/smscv1/ussd.proto

package smscv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	USSDAdapterService_SendUSSD_FullMethodName   = "/smsc.v1.USSDAdapterService/SendUSSD"
	USSDAdapterService_StreamUSSD_FullMethodName = "/smsc.v1.USSDAdapterService/StreamUSSD"
	USSDAdapterService_ReplyUSSD_FullMethodName  = "/smsc.v1.USSDAdapterService/ReplyUSSD"
	USSDAdapterService_EndSession_FullMethodName = "/smsc.v1.USSDAdapterService/EndSession"
	USSDAdapterService_GetStatus_FullMethodName  = "/smsc.v1.USSDAdapterService/GetStatus"
)

// USSDAdapterServiceClient is the client API for USSDAdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// USSDAdapterService handles USSD sessions over downstream networks.
type USSDAdapterServiceClient interface {
	// Initiate a network-originated USSD push to a subscriber.
	SendUSSD(ctx context.Context, in *SendUSSDRequest, opts ...grpc.CallOption) (*SendUSSDResponse, error)
	// Server-streaming channel for subscriber-initiated USSD requests.
	StreamUSSD(ctx context.Context, in *StreamUSSDRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[USSDEvent], error)
	// Reply to an active subscriber-initiated USSD session.
	ReplyUSSD(ctx context.Context, in *ReplyUSSDRequest, opts ...grpc.CallOption) (*ReplyUSSDResponse, error)
	// End a USSD session without sending a response.
	EndSession(ctx context.Context, in *EndUSSDSessionRequest, opts ...grpc.CallOption) (*EndUSSDSessionResponse, error)
	// Query adapter health and USSD counters.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*USSDAdapterStatus, error)
}

type uSSDAdapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUSSDAdapterServiceClient(cc grpc.ClientConnInterface) USSDAdapterServiceClient {
	return &uSSDAdapterServiceClient{cc}
}

func (c *uSSDAdapterServiceClient) SendUSSD(ctx context.Context, in *SendUSSDRequest, opts ...grpc.CallOption) (*SendUSSDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendUSSDResponse)
	err := c.cc.Invoke(ctx, USSDAdapterService_SendUSSD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSSDAdapterServiceClient) StreamUSSD(ctx context.Context, in *StreamUSSDRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[USSDEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &USSDAdapterService_ServiceDesc.Streams[0], USSDAdapterService_StreamUSSD_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUSSDRequest, USSDEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type USSDAdapterService_StreamUSSDClient = grpc.ServerStreamingClient[USSDEvent]

func (c *uSSDAdapterServiceClient) ReplyUSSD(ctx context.Context, in *ReplyUSSDRequest, opts ...grpc.CallOption) (*ReplyUSSDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyUSSDResponse)
	err := c.cc.Invoke(ctx, USSDAdapterService_ReplyUSSD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSSDAdapterServiceClient) EndSession(ctx context.Context, in *EndUSSDSessionRequest, opts ...grpc.CallOption) (*EndUSSDSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndUSSDSessionResponse)
	err := c.cc.Invoke(ctx, USSDAdapterService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uSSDAdapterServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*USSDAdapterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(USSDAdapterStatus)
	err := c.cc.Invoke(ctx, USSDAdapterService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// USSDAdapterServiceServer is the server API for USSDAdapterService service.
// All implementations must embed UnimplementedUSSDAdapterServiceServer
// for forward compatibility.
//
// USSDAdapterService handles USSD sessions over downstream networks.
type USSDAdapterServiceServer interface {
	// Initiate a network-originated USSD push to a subscriber.
	SendUSSD(context.Context, *SendUSSDRequest) (*SendUSSDResponse, error)
	// Server-streaming channel for subscriber-initiated USSD requests.
	StreamUSSD(*StreamUSSDRequest, grpc.ServerStreamingServer[USSDEvent]) error
	// Reply to an active subscriber-initiated USSD session.
	ReplyUSSD(context.Context, *ReplyUSSDRequest) (*ReplyUSSDResponse, error)
	// End a USSD session without sending a response.
	EndSession(context.Context, *EndUSSDSessionRequest) (*EndUSSDSessionResponse, error)
	// Query adapter health and USSD counters.
	GetStatus(context.Context, *GetStatusRequest) (*USSDAdapterStatus, error)
	mustEmbedUnimplementedUSSDAdapterServiceServer()
}

// UnimplementedUSSDAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUSSDAdapterServiceServer struct{}

func (UnimplementedUSSDAdapterServiceServer) SendUSSD(context.Context, *SendUSSDRequest) (*SendUSSDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendUSSD not implemented")
}
func (UnimplementedUSSDAdapterServiceServer) StreamUSSD(*StreamUSSDRequest, grpc.ServerStreamingServer[USSDEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamUSSD not implemented")
}
func (UnimplementedUSSDAdapterServiceServer) ReplyUSSD(context.Context, *ReplyUSSDRequest) (*ReplyUSSDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyUSSD not implemented")
}
func (UnimplementedUSSDAdapterServiceServer) EndSession(context.Context, *EndUSSDSessionRequest) (*EndUSSDSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedUSSDAdapterServiceServer) GetStatus(context.Context, *GetStatusRequest) (*USSDAdapterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedUSSDAdapterServiceServer) mustEmbedUnimplementedUSSDAdapterServiceServer() {}
func (UnimplementedUSSDAdapterServiceServer) testEmbeddedByValue()                            {}

// UnsafeUSSDAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to USSDAdapterServiceServer will
// result in compilation errors.
type UnsafeUSSDAdapterServiceServer interface {
	mustEmbedUnimplementedUSSDAdapterServiceServer()
}

func RegisterUSSDAdapterServiceServer(s grpc.ServiceRegistrar, srv USSDAdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedUSSDAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&USSDAdapterService_ServiceDesc, srv)
}

func _USSDAdapterService_SendUSSD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUSSDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USSDAdapterServiceServer).SendUSSD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USSDAdapterService_SendUSSD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USSDAdapterServiceServer).SendUSSD(ctx, req.(*SendUSSDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USSDAdapterService_StreamUSSD_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamUSSDRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(USSDAdapterServiceServer).StreamUSSD(m, &grpc.GenericServerStream[StreamUSSDRequest, USSDEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type USSDAdapterService_StreamUSSDServer = grpc.ServerStreamingServer[USSDEvent]

func _USSDAdapterService_ReplyUSSD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyUSSDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USSDAdapterServiceServer).ReplyUSSD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USSDAdapterService_ReplyUSSD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USSDAdapterServiceServer).ReplyUSSD(ctx, req.(*ReplyUSSDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USSDAdapterService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndUSSDSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USSDAdapterServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USSDAdapterService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USSDAdapterServiceServer).EndSession(ctx, req.(*EndUSSDSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _USSDAdapterService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USSDAdapterServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USSDAdapterService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USSDAdapterServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// USSDAdapterService_ServiceDesc is the grpc.ServiceDesc for USSDAdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var USSDAdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smsc.v1.USSDAdapterService",
	HandlerType: (*USSDAdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUSSD",
			Handler:    _USSDAdapterService_SendUSSD_Handler,
		},
		{
			MethodName: "ReplyUSSD",
			Handler:    _USSDAdapterService_ReplyUSSD_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _USSDAdapterService_EndSession_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _USSDAdapterService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUSSD",
			Handler:       _USSDAdapterService_StreamUSSD_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/smscv1/ussd.proto",
}
