// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/smscv1/ussd.proto

package smscv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type USSDEventType int32

const (
	USSDEventType_USSD_EVENT_UNSPECIFIED USSDEventType = 0
	USSDEventType_USSD_REQUEST           USSDEventType = 1 // Subscriber dialed a USSD code (*123#)
	USSDEventType_USSD_NOTIFY            USSDEventType = 2 // Network notification
	USSDEventType_USSD_RESPONSE          USSDEventType = 3 // Subscriber replied to a menu prompt
	USSDEventType_USSD_ABORT             USSDEventType = 4 // Session aborted by subscriber or network
)

// Enum value maps for USSDEventType.
var (
	USSDEventType_name = map[int32]string{
		0: "USSD_EVENT_UNSPECIFIED",
		1: "USSD_REQUEST",
		2: "USSD_NOTIFY",
		3: "USSD_RESPONSE",
		4: "USSD_ABORT",
	}
	USSDEventType_value = map[string]int32{
		"USSD_EVENT_UNSPECIFIED": 0,
		"USSD_REQUEST":           1,
		"USSD_NOTIFY":            2,
		"USSD_RESPONSE":          3,
		"USSD_ABORT":             4,
	}
)

func (x USSDEventType) Enum() *USSDEventType {
	p := new(USSDEventType)
	*p = x
	return p
}

func (x USSDEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (USSDEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smscv1_ussd_proto_enumTypes[0].Descriptor()
}

func (USSDEventType) Type() protoreflect.EnumType {
	return &file_proto_smscv1_ussd_proto_enumTypes[0]
}

func (x USSDEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use USSDEventType.Descriptor instead.
func (USSDEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{0}
}

type SendUSSDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // Gateway-assigned session ID
	Msisdn        string                 `protobuf:"bytes,2,opt,name=msisdn,proto3" json:"msisdn,omitempty"`                            // Target subscriber (E.164)
	UssdString    string                 `protobuf:"bytes,3,opt,name=ussd_string,json=ussdString,proto3" json:"ussd_string,omitempty"`  // USSD message/menu text
	DataCoding    uint32                 `protobuf:"varint,4,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"` // CBS data coding (0x0F = GSM 7-bit default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUSSDRequest) Reset() {
	*x = SendUSSDRequest{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUSSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUSSDRequest) ProtoMessage() {}

func (x *SendUSSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUSSDRequest.ProtoReflect.Descriptor instead.
func (*SendUSSDRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{0}
}

func (x *SendUSSDRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendUSSDRequest) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

func (x *SendUSSDRequest) GetUssdString() string {
	if x != nil {
		return x.UssdString
	}
	return ""
}

func (x *SendUSSDRequest) GetDataCoding() uint32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

type SendUSSDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status         uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0 = success
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResponseString string                 `protobuf:"bytes,4,opt,name=response_string,json=responseString,proto3" json:"response_string,omitempty"` // Subscriber's response (if any)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendUSSDResponse) Reset() {
	*x = SendUSSDResponse{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUSSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUSSDResponse) ProtoMessage() {}

func (x *SendUSSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUSSDResponse.ProtoReflect.Descriptor instead.
func (*SendUSSDResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{1}
}

func (x *SendUSSDResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendUSSDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendUSSDResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SendUSSDResponse) GetResponseString() string {
	if x != nil {
		return x.ResponseString
	}
	return ""
}

type StreamUSSDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUSSDRequest) Reset() {
	*x = StreamUSSDRequest{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUSSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUSSDRequest) ProtoMessage() {}

func (x *StreamUSSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUSSDRequest.ProtoReflect.Descriptor instead.
func (*StreamUSSDRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{2}
}

func (x *StreamUSSDRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type USSDEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          USSDEventType          `protobuf:"varint,2,opt,name=type,proto3,enum=smsc.v1.USSDEventType" json:"type,omitempty"`
	Msisdn        string                 `protobuf:"bytes,3,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	UssdString    string                 `protobuf:"bytes,4,opt,name=ussd_string,json=ussdString,proto3" json:"ussd_string,omitempty"` // USSD code or menu response from subscriber
	DataCoding    uint32                 `protobuf:"varint,5,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"`
	DialogId      int64                  `protobuf:"varint,6,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"` // MAP dialog ID (for routing replies)
	InvokeId      int32                  `protobuf:"varint,7,opt,name=invoke_id,json=invokeId,proto3" json:"invoke_id,omitempty"` // MAP invoke ID (for routing replies)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *USSDEvent) Reset() {
	*x = USSDEvent{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USSDEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USSDEvent) ProtoMessage() {}

func (x *USSDEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USSDEvent.ProtoReflect.Descriptor instead.
func (*USSDEvent) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{3}
}

func (x *USSDEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *USSDEvent) GetType() USSDEventType {
	if x != nil {
		return x.Type
	}
	return USSDEventType_USSD_EVENT_UNSPECIFIED
}

func (x *USSDEvent) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

func (x *USSDEvent) GetUssdString() string {
	if x != nil {
		return x.UssdString
	}
	return ""
}

func (x *USSDEvent) GetDataCoding() uint32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

func (x *USSDEvent) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *USSDEvent) GetInvokeId() int32 {
	if x != nil {
		return x.InvokeId
	}
	return 0
}

type ReplyUSSDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DialogId       int64                  `protobuf:"varint,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	InvokeId       int32                  `protobuf:"varint,3,opt,name=invoke_id,json=invokeId,proto3" json:"invoke_id,omitempty"`
	ResponseString string                 `protobuf:"bytes,4,opt,name=response_string,json=responseString,proto3" json:"response_string,omitempty"` // Response/menu text to send
	DataCoding     uint32                 `protobuf:"varint,5,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"`
	EndSession     bool                   `protobuf:"varint,6,opt,name=end_session,json=endSession,proto3" json:"end_session,omitempty"` // True to close the dialog after this response
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyUSSDRequest) Reset() {
	*x = ReplyUSSDRequest{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyUSSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUSSDRequest) ProtoMessage() {}

func (x *ReplyUSSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUSSDRequest.ProtoReflect.Descriptor instead.
func (*ReplyUSSDRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyUSSDRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplyUSSDRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *ReplyUSSDRequest) GetInvokeId() int32 {
	if x != nil {
		return x.InvokeId
	}
	return 0
}

func (x *ReplyUSSDRequest) GetResponseString() string {
	if x != nil {
		return x.ResponseString
	}
	return ""
}

func (x *ReplyUSSDRequest) GetDataCoding() uint32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

func (x *ReplyUSSDRequest) GetEndSession() bool {
	if x != nil {
		return x.EndSession
	}
	return false
}

type ReplyUSSDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyUSSDResponse) Reset() {
	*x = ReplyUSSDResponse{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyUSSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUSSDResponse) ProtoMessage() {}

func (x *ReplyUSSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUSSDResponse.ProtoReflect.Descriptor instead.
func (*ReplyUSSDResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyUSSDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReplyUSSDResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EndUSSDSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DialogId      int64                  `protobuf:"varint,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndUSSDSessionRequest) Reset() {
	*x = EndUSSDSessionRequest{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndUSSDSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndUSSDSessionRequest) ProtoMessage() {}

func (x *EndUSSDSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndUSSDSessionRequest.ProtoReflect.Descriptor instead.
func (*EndUSSDSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{6}
}

func (x *EndUSSDSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndUSSDSessionRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

type EndUSSDSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndUSSDSessionResponse) Reset() {
	*x = EndUSSDSessionResponse{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndUSSDSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndUSSDSessionResponse) ProtoMessage() {}

func (x *EndUSSDSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndUSSDSessionResponse.ProtoReflect.Descriptor instead.
func (*EndUSSDSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{7}
}

func (x *EndUSSDSessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EndUSSDSessionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// USSD-specific status.
type USSDAdapterStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Base              *AdapterStatus         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SessionsInitiated int64                  `protobuf:"varint,2,opt,name=sessions_initiated,json=sessionsInitiated,proto3" json:"sessions_initiated,omitempty"`
	SessionsReceived  int64                  `protobuf:"varint,3,opt,name=sessions_received,json=sessionsReceived,proto3" json:"sessions_received,omitempty"`
	SessionsActive    int64                  `protobuf:"varint,4,opt,name=sessions_active,json=sessionsActive,proto3" json:"sessions_active,omitempty"`
	SessionsFailed    int64                  `protobuf:"varint,5,opt,name=sessions_failed,json=sessionsFailed,proto3" json:"sessions_failed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *USSDAdapterStatus) Reset() {
	*x = USSDAdapterStatus{}
	mi := &file_proto_smscv1_ussd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USSDAdapterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USSDAdapterStatus) ProtoMessage() {}

func (x *USSDAdapterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smscv1_ussd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USSDAdapterStatus.ProtoReflect.Descriptor instead.
func (*USSDAdapterStatus) Descriptor() ([]byte, []int) {
	return file_proto_smscv1_ussd_proto_rawDescGZIP(), []int{8}
}

func (x *USSDAdapterStatus) GetBase() *AdapterStatus {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *USSDAdapterStatus) GetSessionsInitiated() int64 {
	if x != nil {
		return x.SessionsInitiated
	}
	return 0
}

func (x *USSDAdapterStatus) GetSessionsReceived() int64 {
	if x != nil {
		return x.SessionsReceived
	}
	return 0
}

func (x *USSDAdapterStatus) GetSessionsActive() int64 {
	if x != nil {
		return x.SessionsActive
	}
	return 0
}

func (x *USSDAdapterStatus) GetSessionsFailed() int64 {
	if x != nil {
		return x.SessionsFailed
	}
	return 0
}

var File_proto_smscv1_ussd_proto protoreflect.FileDescriptor

const file_proto_smscv1_ussd_proto_rawDesc = "" +
	"\n" +
	"\x17proto/smscv1/ussd.proto\x12\asmsc.v1\x1a\x19proto/smscv1/common.proto\"\x8a\x01\n" +
	"\x0fSendUSSDRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06msisdn\x18\x02 \x01(\tR\x06msisdn\x12\x1f\n" +
	"\vussd_string\x18\x03 \x01(\tR\n" +
	"ussdString\x12\x1f\n" +
	"\vdata_coding\x18\x04 \x01(\rR\n" +
	"dataCoding\"\x97\x01\n" +
	"\x10SendUSSDResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0fresponse_string\x18\x04 \x01(\tR\x0eresponseString\"0\n" +
	"\x11StreamUSSDRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xea\x01\n" +
	"\tUSSDEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.smsc.v1.USSDEventTypeR\x04type\x12\x16\n" +
	"\x06msisdn\x18\x03 \x01(\tR\x06msisdn\x12\x1f\n" +
	"\vussd_string\x18\x04 \x01(\tR\n" +
	"ussdString\x12\x1f\n" +
	"\vdata_coding\x18\x05 \x01(\rR\n" +
	"dataCoding\x12\x1b\n" +
	"\tdialog_id\x18\x06 \x01(\x03R\bdialogId\x12\x1b\n" +
	"\tinvoke_id\x18\a \x01(\x05R\binvokeId\"\xd6\x01\n" +
	"\x10ReplyUSSDRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\x03R\bdialogId\x12\x1b\n" +
	"\tinvoke_id\x18\x03 \x01(\x05R\binvokeId\x12'\n" +
	"\x0fresponse_string\x18\x04 \x01(\tR\x0eresponseString\x12\x1f\n" +
	"\vdata_coding\x18\x05 \x01(\rR\n" +
	"dataCoding\x12\x1f\n" +
	"\vend_session\x18\x06 \x01(\bR\n" +
	"endSession\"P\n" +
	"\x11ReplyUSSDResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"S\n" +
	"\x15EndUSSDSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\x03R\bdialogId\"U\n" +
	"\x16EndUSSDSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xed\x01\n" +
	"\x11USSDAdapterStatus\x12*\n" +
	"\x04base\x18\x01 \x01(\v2\x16.smsc.v1.AdapterStatusR\x04base\x12-\n" +
	"\x12sessions_initiated\x18\x02 \x01(\x03R\x11sessionsInitiated\x12+\n" +
	"\x11sessions_received\x18\x03 \x01(\x03R\x10sessionsReceived\x12'\n" +
	"\x0fsessions_active\x18\x04 \x01(\x03R\x0esessionsActive\x12'\n" +
	"\x0fsessions_failed\x18\x05 \x01(\x03R\x0esessionsFailed*q\n" +
	"\rUSSDEventType\x12\x1a\n" +
	"\x16USSD_EVENT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUSSD_REQUEST\x10\x01\x12\x0f\n" +
	"\vUSSD_NOTIFY\x10\x02\x12\x11\n" +
	"\rUSSD_RESPONSE\x10\x03\x12\x0e\n" +
	"\n" +
	"USSD_ABORT\x10\x042\xec\x02\n" +
	"\x12USSDAdapterService\x12?\n" +
	"\bSendUSSD\x12\x18.smsc.v1.SendUSSDRequest\x1a\x19.smsc.v1.SendUSSDResponse\x12>\n" +
	"\n" +
	"StreamUSSD\x12\x1a.smsc.v1.StreamUSSDRequest\x1a\x12.smsc.v1.USSDEvent0\x01\x12B\n" +
	"\tReplyUSSD\x12\x19.smsc.v1.ReplyUSSDRequest\x1a\x1a.smsc.v1.ReplyUSSDResponse\x12M\n" +
	"\n" +
	"EndSession\x12\x1e.smsc.v1.EndUSSDSessionRequest\x1a\x1f.smsc.v1.EndUSSDSessionResponse\x12B\n" +
	"\tGetStatus\x12\x19.smsc.v1.GetStatusRequest\x1a\x1a.smsc.v1.USSDAdapterStatusB@\n" +
	"\x16com.idnteq.ss7gw.protoZ&github.com/idnteq/go-smsc/proto/smscv1b\x06proto3"

var (
	file_proto_smscv1_ussd_proto_rawDescOnce sync.Once
	file_proto_smscv1_ussd_proto_rawDescData []byte
)

func file_proto_smscv1_ussd_proto_rawDescGZIP() []byte {
	file_proto_smscv1_ussd_proto_rawDescOnce.Do(func() {
		file_proto_smscv1_ussd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smscv1_ussd_proto_rawDesc), len(file_proto_smscv1_ussd_proto_rawDesc)))
	})
	return file_proto_smscv1_ussd_proto_rawDescData
}

var file_proto_smscv1_ussd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_smscv1_ussd_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_smscv1_ussd_proto_goTypes = []any{
	(USSDEventType)(0),             // 0: smsc.v1.USSDEventType
	(*SendUSSDRequest)(nil),        // 1: smsc.v1.SendUSSDRequest
	(*SendUSSDResponse)(nil),       // 2: smsc.v1.SendUSSDResponse
	(*StreamUSSDRequest)(nil),      // 3: smsc.v1.StreamUSSDRequest
	(*USSDEvent)(nil),              // 4: smsc.v1.USSDEvent
	(*ReplyUSSDRequest)(nil),       // 5: smsc.v1.ReplyUSSDRequest
	(*ReplyUSSDResponse)(nil),      // 6: smsc.v1.ReplyUSSDResponse
	(*EndUSSDSessionRequest)(nil),  // 7: smsc.v1.EndUSSDSessionRequest
	(*EndUSSDSessionResponse)(nil), // 8: smsc.v1.EndUSSDSessionResponse
	(*USSDAdapterStatus)(nil),      // 9: smsc.v1.USSDAdapterStatus
	(*AdapterStatus)(nil),          // 10: smsc.v1.AdapterStatus
	(*GetStatusRequest)(nil),       // 11: smsc.v1.GetStatusRequest
}
var file_proto_smscv1_ussd_proto_depIdxs = []int32{
	0,  // 0: smsc.v1.USSDEvent.type:type_name -> smsc.v1.USSDEventType
	10, // 1: smsc.v1.USSDAdapterStatus.base:type_name -> smsc.v1.AdapterStatus
	1,  // 2: smsc.v1.USSDAdapterService.SendUSSD:input_type -> smsc.v1.SendUSSDRequest
	3,  // 3: smsc.v1.USSDAdapterService.StreamUSSD:input_type -> smsc.v1.StreamUSSDRequest
	5,  // 4: smsc.v1.USSDAdapterService.ReplyUSSD:input_type -> smsc.v1.ReplyUSSDRequest
	7,  // 5: smsc.v1.USSDAdapterService.EndSession:input_type -> smsc.v1.EndUSSDSessionRequest
	11, // 6: smsc.v1.USSDAdapterService.GetStatus:input_type -> smsc.v1.GetStatusRequest
	2,  // 7: smsc.v1.USSDAdapterService.SendUSSD:output_type -> smsc.v1.SendUSSDResponse
	4,  // 8: smsc.v1.USSDAdapterService.StreamUSSD:output_type -> smsc.v1.USSDEvent
	6,  // 9: smsc.v1.USSDAdapterService.ReplyUSSD:output_type -> smsc.v1.ReplyUSSDResponse
	8,  // 10: smsc.v1.USSDAdapterService.EndSession:output_type -> smsc.v1.EndUSSDSessionResponse
	9,  // 11: smsc.v1.USSDAdapterService.GetStatus:output_type -> smsc.v1.USSDAdapterStatus
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_smscv1_ussd_proto_init() }
func file_proto_smscv1_ussd_proto_init() {
	if File_proto_smscv1_ussd_proto != nil {
		return
	}
	file_proto_smscv1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smscv1_ussd_proto_rawDesc), len(file_proto_smscv1_ussd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smscv1_ussd_proto_goTypes,
		DependencyIndexes: file_proto_smscv1_ussd_proto_depIdxs,
		EnumInfos:         file_proto_smscv1_ussd_proto_enumTypes,
		MessageInfos:      file_proto_smscv1_ussd_proto_msgTypes,
	}.Build()
	File_proto_smscv1_ussd_proto = out.File
	file_proto_smscv1_ussd_proto_goTypes = nil
	file_proto_smscv1_ussd_proto_depIdxs = nil
}
